
### book create
POST localhost:8081/book/create
Content-Type: application/json

{
  "title": "5",
  "author": "Ravshan",
  "publishYear": "1998-12-12",
  "amount": "4",
  "visible": "true"
}

### book list
GET localhost:8081/book/bookList

### book getById
GET localhost:8081/book/get/1

### book update
PUT localhost:8081/book/update/1
Content-Type: application/json

{
  "title": "o'tgan kunlar",
  "author": "Primqul Qodirov",
  "publishYear": "1965-12-10",
  "amount": "4",
  "visible": "true"
}

### book delete
DELETE localhost:8081/book/delete/4
Content-Type: application/json
